feature/creating-purchasing-adjustments1
softwarealcaldiagirardota/festivals-fe pull request #3
Opened 2024-07-29 23:26 UTC by Arlex296

Finish adjusting the purchases tab by adding the kg quantity

2024-07-29 23:34 UTC, softwarealcaldiagirardota requested changes

2024-07-29 23:34 UTC, softwarealcaldiagirardota commented on src/App.tsx
> +<Route
Corregir alineación según las otras

2024-07-29 23:34 UTC, softwarealcaldiagirardota commented on src/components/Actions copy/index.tsx
> +      <Title text={`${formatter.format(text)}${isSales ? " ud.": " kg"}`}type="small" />
Llevar esto a una constante en utils.ts ejemplo

const unidades = " ud."
const kg = " kg."

2024-07-29 23:34 UTC, softwarealcaldiagirardota commented on src/components/SalesReported/index.tsx
> +        {`${formatter.format(Number(value))} ${isSalesReported ? "ud." : "kg"}`}
Aquí lo mismo Llevar esto a una constante en utils.ts ejemplo

const unidades = " ud."
const kg = " kg."

2024-07-29 23:34 UTC, softwarealcaldiagirardota commented on src/pages/company-reports/buys/details/index.tsx
> +const salesDetail = [
cambiar por buysDetails

2024-07-29 23:37 UTC, Arlex296 commented on src/App.tsx
> +<Route
Corregido

2024-07-30 00:01 UTC, Arlex296 commented on src/components/Actions copy/index.tsx
> +      <Title text={`${formatter.format(text)}${isSales ? " ud.": " kg"}`}type="small" />
Corregido

2024-07-30 00:01 UTC, Arlex296 commented on src/components/SalesReported/index.tsx
> +        {`${formatter.format(Number(value))} ${isSalesReported ? "ud." : "kg"}`}
Corregido

2024-07-30 00:10 UTC, softwarealcaldiagirardota approved these changes

2024-07-30 00:11 UTC, merged